name: Run Python Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread oauth2client playwright

      - name: Write service account key
        
        run: echo "${{ secrets.GOOGLE_SA_JSON }}" > service_account.json
        
        env:
          GOOGLE_SA_KEYFILE: service_account.json

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Run script
        run: python trends_fetcher.py
        env:
          
          GOOGLE_SA_KEYFILE: service_account.json
