# .github/workflows/Pytrends.yml
name: Run Trends Scraper

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * *'  # KST 00:00
    - cron: '0 19 * * *'  # KST 04:00
    - cron: '0 23 * * *'  # KST 08:00
    - cron: '0 3 * * *'   # KST 12:00
    - cron: '0 7 * * *'   # KST 16:00
    - cron: '0 11 * * *'  # KST 20:00

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # your service account JSON stored as a GitHub secret
      GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread oauth2client playwright

      - name: Install Chromium system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 \
            libgbm1 libasound2-data libpangocairo-1.0-0 \
            libxss1 libpci3 libxshmfence1

      - name: Install Playwright dependencies
        run: |
          python -m playwright install-deps
          python -m playwright install

      - name: Run scraper
        run: python trends_fetcher.py
